steps:
  - label: "Deploying hooks-todos server"
    command: "yarn run deploy:ci"
    plugins:
      - docker-compose#v3.1.0:
          run: server
          env:
            - AWS_DEFAULT_REGION
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY