# serverless.yml

service: apollo-lambda
provider:
  name: aws
  runtime: nodejs12.x

# resources
resources: # CloudFormation template syntax from here on.
  Resources:
    todoListTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: todoListTable
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: complete
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: complete
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1


# functions
functions:
  graphql:
    # this is formatted as <FILENAME>.<HANDLER>
    handler: graphql.graphqlHandler
    events:
    - http:
        path: graphql
        method: post
        cors: true
    - http:
        path: graphql
        method: get
        cors: true